spring:
    mvc:
        pathmatch:
            matching-strategy: ant-path-matcher
    jpa:
        database-platform: org.hibernate.dialect.SQLServerDialect
        hibernate:
            ddl-auto: none
    datasource:
        url: jdbc:sqlserver://172.23.206.211:1403;databaseName=Northwind;encrypt=true;trustServerCertificate=true;
        username: sa
        password: "!Passw0rd"
